server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
#          # user-service
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates: #조건식
#            - Path=/user-service/**
        # user-service => 로그인
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: #조건식
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # user-service => 회원가입
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: #조건식
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # user-service => 기타
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: #조건식
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # catalog-service
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates: #조건식
            - Path=/catalog-service/**
        # order-service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates: #조건식
            - Path=/order-service/**
        # other service
        - id: first-service
          uri: lb://MY-FIRST-SERVICE
          predicates: # ???
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2 # key, value
#            - AddResponseHeader=first-response, first-response-header2 # key, value
            - CustomFilter
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates: # whr
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2 # key, value
#            - AddResponseHeader=second-response, second-response-header2 # key, value
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true

token:
  secret: user_token